use Analysis
SELECT * FROM INFORMATION_SCHEMA.TABLES;
select * from customer_shopping_behavior;

--Q1.What is the total revenue generated by male vs. female customers?
select gender,
sum(purchase_amount)as revenue from customer_shopping_behavior
group by gender;

--Q2.Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer_shopping_behavior
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer_shopping_behavior
);

--Q3.Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(CAST(review_rating AS decimal  (10,2))), 2) AS [Average Product Rating]
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS DECIMAL(10,2))) DESC;

--Q4.Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2)
FROM customer_shopping_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend, 
round(sum(purchase_amount),2) as total_revenue
from customer_shopping_behavior
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6.Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100*sum(case when discount_applied='yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_shopping_behavior
group by item_purchased
order by discount_rate desc;

--Q7.Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
case
    when previous_purchases=1then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else'loyal'
    end as customer_segment
from customer_shopping_behavior 
)
select customer_segment,count(*) as "number of customer"
from customer_type
group by customer_segment;

--Q8.What are the top 3 most purchased products within each category? 
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count (customer_id) desc) as item_rank
from customer_shopping_behavior
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behavior
where previous_purchases>5
group by subscription_status;

--Q10.What is the revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as total_revenue
from customer_shopping_behavior
group by age_group
order by total_revenue desc;
